# Generated by Django 4.2 on 2023-04-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_feriado', models.CharField(max_length=100)),
                ('dia', models.IntegerField(max_length=2)),
                ('mes', models.IntegerField(max_length=2)),
                ('modificado_em', models.DateField(auto_now=True)),
            ],
        ),
    ]
