# Generated by Django 4.2 on 2023-04-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriadomodel',
            name='dia',
            field=models.IntegerField(verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='feriadomodel',
            name='mes',
            field=models.IntegerField(verbose_name='mes'),
        ),
    ]
